### ISSUE TITLE
[feature request] custom slack icon

### ISSUE THREAD

**Issue by cnf** [TheGoddessInari/hamsket#127]
Use the team icon from the slack server and/or let us set custom icons for slack servers

also see #97, and https://github.com/ramboxapp/community-edition/issues/113

Right now, all slack instances have the same icon, which is confusing. Slack lets owners change their icon, it would be nice if the icon in hamsket reflected this.

**Comment by TheGoddessInari** [comment]
Slack is already using the server-set icon for slack servers where that's set. I'll look into custom icons in general this week hopefully.

**Comment by cnf** [comment]
Hmm, interesting, it is not showing the server set icon for me...

-- 
Frank Rosquin

**Comment by TheGoddessInari** [comment]
OS/version/etc? I kinda need the info that's asked in the form to narrow down what's going on.

The icon loading behavior was fixed in e2e6c2abe7bb398d0877beae249fb1dd8dba71c7, and then delays 1s to make sure that Slack has time to actually load the menu that it gets the icon from.

It won't use a separate icon if the icon is 'blank' on the server side (which just shows up as a letter on Slack itself). It also won't always show an icon if the server takes more than 1s to load the menu.

There's nothing I could do about the latter but increase the delay before it checks further.

It also won't load the icon if slack (somehow) for you is using an icon class different than `.c-team_icon`, but that's the current one. I'll look into it a bit more later today, but realistically, at most I could tweak the delay, or make it reload the icon every so often, not necessarily a cheap or seamless action since it has to open a menu on the page.

I looked, and there's no real way to use the Slack API to more reliably retrieve that information without the user passing their own token in. I could look into supporting that, but that's not even slightly user-friendly. 🦊

**Comment by cnf** [comment]
Ha, sorry about that. I replied from my phone, and didn't click that I made it from a feature request to a bug report :p 

The Icon does work on Franz, and the official slack app, if that is any reference.

OS is macOS 10.14.6, 
Version: 0.5.18
Platform: darwin (x64)
Electron: 5.0.6
Chromium: 73.0.3683.121
Node: 12.0.0
BuildVersion: 61fa8c4 (grafted, HEAD, tag: nightly, origin/master) Sun, 7 Jul 2019 12:23:52 -0700

I hope that helps?

<img width="301" alt="image" src="https://user-images.githubusercontent.com/252949/64717708-148de480-d4c5-11e9-98d5-077b5e016e9b.png">

**Comment by TheGoddessInari** [comment]
🦊 This is why. That's an old version!

New packages are named Hamsket and actively developed. If you have a particular need for the old version, I can backport a few of the fixes.

**Comment by cnf** [comment]
hmm, it is the one labeled "latest release" for me. So basically it is fixed in the nightlies?

I don't have a specific need for an "old" version, I just want a stable version on my work machine, hence why I didn't get the nightly :P

**Comment by TheGoddessInari** [comment]
Right-o. I'll include some fixes and push a version later today.

I'm still working on stabilizing a new version, but it seems like that'll come down to some UI fixes.

**Comment by cnf** [comment]
sounds great, thanks!

as a side note, I came here because Franz (of which i was a paid subscriber) was using INSANE amounts of resources, and someone linked me here. So far, hamsket is behaving way way better :P so thanks!

**Comment by TheGoddessInari** [comment]
🦊 Resource usage is always a priority for me. Nobody should have to deal with greedy desktop applications.

**Comment by TheGoddessInari** [comment]
There were builds on devops, but I ended up needing to fix a few more things. Here's the new build. https://github.com/TheGoddessInari/hamsket/releases/tag/0.5.19

**Comment by cnf** [comment]
nice, thanks!

**Comment by TheGoddessInari** [comment]
Sounds like it's effectively fixed. Let me know if it's the case otherwise.
