### ISSUE TITLE
Tray icon disappears after screen lock on Ubuntu 19.10

### ISSUE THREAD

**Issue by beltrame** [TheGoddessInari/hamsket#187]
Hamsket loses the tray icon after locking the screen on Ubuntu 19.10. 

### Steps to reproduce

1. Start hamsket with tray icon enabled
2. Lock screen
3. Unlock

### Expected behavior

Hamsket tray icon should still be present

### Actual behavior

The tray icon disapears

### ENVIRONMENT

Hamsket: v0.6.0 Nightly
OS: Ubuntu 19.10 stock install
Arch: x64

This is an electron/Chromium bugs maybe ([see here](https://bugs.chromium.org/p/chromium/issues/detail?id=1042098)), but there are [workarounds](https://github.com/zulip/zulip-desktop/issues/910#issuecomment-608056150) that might apply here.

**Comment by TheGoddessInari** [comment]
I looked over the link, and all of the related issues. Given that it affects stock Chrome/Chromium, and Chrome says it's straight up a GNOME bug, it isn't really within the scope to fix it, at least, not with running code like that!

If there's a way to work around the issue in native Electron, I'd consider it, but running arbitrary code in the user session like that suggested workaround is beyond the pale.

The problem here has generally been that GNOME is generally quite hostile to anything it considers no longer necessary, while other DEs (tend) to support the relevant standards. AFAIK, GNOME doesn't want to support this, and in fact hasn't for many years,

If a company like Google, with all of its resources and love for GTK+, can't convince GNOME to be a good shepherd, what chance do projects with a single person working on them have?

There are also several issues on https://github.com/ubuntu/gnome-shell-extension-appindicator/issues that **seem** to indicate that the extension providing the support for the systray stuff at all is getting affected too.

I know it sucks and isn't convenient and people really like GNOME, but this is the kind of stuff that they arbitrarily impose on their own users. Neither users nor developers get a say in this.

**Comment by beltrame** [comment]
I'm not entirely sure this is a GNOME bug, as Rambox (which uses an earlier [7.1.12] version of Electron) is not affected. Something has changed with Electron between 7.x and 8.x that made the issue appear... I haven't actually discovered what yet.

**Comment by aravindhp** [comment]
I am seeing this issue too. I do not see this issue with RamBox.

**Comment by beltrame** [comment]
Summary of my findings: the issue is the switch of Chromium from libappindicator to StatusNotifier/DBus (committed to Electron 8+). gnome-shell requires the DBus introspection protocol to be implemented on tray icons and Chromium didn't think it was worth implementing. The implementation is indeed assigned to somebody for Chromium, but I don't see it happening soon. Rambox uses Electron 7.2 so it still uses libappindicator, and therefore doesn't show this issue. 

An **ugly** workaround is to deactivate the tray icon and use an extension to get Hamsket in the tray (e.g. https://extensions.gnome.org/extension/1750/minimize-to-tray/), but then you lose the tray color change when you have notifications.

**Comment by andrekeller** [comment]
This has been fixed for my in the newer electron version, probably due to https://github.com/electron/electron/pull/23926

**Comment by beltrame** [comment]
Yes, works for me as well (interesting backpedaling from electron/chromium)
