### ISSUE TITLE
Google Voice Update Badge Count Broken - and a fix

### ISSUE THREAD

**Issue by waynehoover** [TheGoddessInari/hamsket#214]
### Steps to reproduce

1. Add a Google Voice Service
2. Receive a SMS, Voicemail, or Call to your google voice number
3. Notice there is a badge count in the corresponding area in google voice but the hamsket unread badge doesn't increment

### Expected behavior

The Hamsket unread badge count increments.

### ENVIRONMENT

Version: 0.6.0
Platform: darwin (x64)
Electron: 9.1.0
Chromium: 83.0.4103.122
Node: 12.14.1
BuildVersion: 518e6b0 (grafted, HEAD, tag: nightly, origin/master) Tue, 14 Jul 2020 11:41:17 -0700

This custom badge update JS fixes the issue:
```
let checkUnread = () => {
  let n = 0;
  ['sidenav-calls', 'sidenav-messages', 'sidenav-voicemail'].forEach(function(id) {
    const text = document.querySelector(`a[gv-test-id='${id}']`).text;
    const matches = text.match(/\d+/g);
    matches && (n += parseInt(matches[0]));
  });
  hamsket.updateBadge(n);
};

setInterval(checkUnread, 3e3);
```

PR to fix: https://github.com/TheGoddessInari/hamsket/pull/215

**Comment by TheGoddessInari** [comment]
Sorry for the delay.
This is a good heads up, but the code isn't equivalent to how it was before.
You're using a regex against the text of the navItemList, when you could be matching the navItemBadge and use innerHTML or innerText directly.

It also happened to make me remember that many uses of `parseInt` in the shipped unread code are guarded inconsistently or not at all. This makes me think I should include a guarded function in the service API for the scripts to use.

This probably should use the querySelectorAll on the unrolled string rather than querySelector 3 different times.

**Comment by waynehoover** [comment]
Sounds good, are you going to make this change or I can. It seems to have been broken for quite some time.

**Comment by TheGoddessInari** [comment]
I can, just didn't want to uncredit you, as it were. But Co-authored-by should work.
If there isn't an issue filed, I may not notice. It wouldn't be very realistic for me to run every service 24/7, either.
I'm mostly happy when people let me know stuff, though. :)

**Comment by TheGoddessInari** [comment]
Should work with a8942df now.
