### ISSUE TITLE
Release policy

### ISSUE THREAD

**Issue by jlkDE** [TheGoddessInari/hamsket#217]
Hi,

thanks for maintaining this as Free Software! I maintain my installation as [package](https://build.opensuse.org/package/show/home:jlkDE/hamsket) for openSUSE. Currently I am packaging the last release, e.g. 0.5.20 from October 2019.
Can you tell me if there is a plan regarding new numbered releases in the future? If no versioning concept is planned, I will switch to nightly builds instead.

**Comment by TheGoddessInari** [comment]
Hi, thanks for the interest.

I really want there to be usual, regular, numbered releases, but the problem has largely been that Electron itself is fairly unstable and prone to regression (no matter which builds you track), and that Google is still effectively blocking Electron apps from actually directly inter-operating with Google properties without lying about being Firefox(!) instead. Since this then causes misrendering, broken links, and other problems, it's hard to come up with a way to actually convincingly make up a release that seems reasonably stable to end users.

At least, since I've been all on my own. I'd be happy for any insight, but Google's interference in things was kinda the last straw in making it astoundingly difficult to release a "stable" version, when really popular services no longer work because they simply stopped liking that Electron exists.

Ideally there would exist a non-Chrome-based browser embedding that could be used, so all of the most absurd problems could hopefully be avoided, but the only attempt at that that I'm aware of (Mozilla's Servo) does not yet have an actual embedding.

**Comment by rodneyrod** [comment]
I think that QtWebEngine (Blink) or Web/Epiphany (Webkit2) might be better choices for embedding, I believe that some of the firefox forks have also tried to make it easier to allow their engines to be used for embedding.

**Comment by TheGoddessInari** [comment]
I think I fixed the Google stuff in 4508c9e.

Other Blink/Webkit embeddings would have the same issue, not counting QtWebkit's issues with always being severely out of date.
I'm not aware of any active Gecko-based embeddings since the mid-2000s or so.

With some luck, there should be a 0.6.0 actual version soon, but there are still some pending issues to fix.

**Comment by jlkDE** [comment]
Hey,

thanks for these insights, I really appreciate and them and completely understand your point.
As long as the numbered version concept is not deprecated, I will continue to package the stable releases as long as there are no strong reasons to incorporate the current upstream, even if they are somehow outdated. In the future, I might attempt to package an automated nightly build.

**Comment by TheGoddessInari** [comment]
For my sanity, I should look to see if there's a way to do truly automated nightly builds on my end via Github Actions. Azure DevOps wasn't terribly interested when I suggested letting their github integration deal well with daily/nightly builds.

**Comment by gschaffner** [comment]
@TheGoddessInari I've started work on a GH Action to build and release nightly. So far it is building only for Linux. See https://github.com/gschaffner/hamsket/runs/936238948

Am I correct that building for Windows and macOS requires compiling on Windows and macOS machines? If this is the case, it shouldn't be too difficult to build for Windows and macOS---we'd mostly just have to translate the Sencha install step to work on Windows and macOS. If you have been building nightlies on Windows and macOS machines you may be more familiar with how to do this (see: powershell, macOS) than me.
