### ISSUE TITLE
Can't close service tabs

### ISSUE THREAD

**Issue by kalimba666** [TheGoddessInari/hamsket#236]
### Steps to reproduce

1. I have ubuntu, Groovy Gorilla
2. Opened Rambox-OS/hamsket
3. Opened service Whatsapp, service Messenger (unfortunately two times)
4. Can't close a tab of a service. Means, if you activate a service, it is always open.

### Expected behavior

The service's tab should have a "x" to close it.

### Actual behavior

Can't close a single service tab.

### ENVIRONMENT

> Hamsket: 
Version: 0.5.20
Plattform: linux (x64)
Electron: 5.0.11
Chromium: 73.0.3683.121
Node: 12.0.0
BuildVersion: fd21604 (grafted, HEAD, origin/rambox-0.5) Mon, 21 Oct 2019 06:55:30 -0700

> OS: Groovy Gorilla, I think it's 20.10

> Arch: x64

> BuildVersion: fd21604 (grafted, HEAD, origin/rambox-0.5) Mon, 21 Oct 2019 06:55:30 -0700

> Does this happen upstream: Don't know what this means.

**Comment by TheGoddessInari** [comment]
You uncheck the service to disable it. When you recheck it, it'll turn back on. This is for keeping services open in general rather efficiently (by default).

> Does this happen upstream: Don't know what this means.

It means Hamsket was forked from Rambox due to their (at the time) total unwillingness to maintain, or be responsive to patches. Largely, they're still unresponsive to security and many other things, so the fork continues.
