### ISSUE TITLE
custom services sharing sessions?

### ISSUE THREAD

**Issue by ikenichiro** [TheGoddessInari/hamsket#286]
### Steps to reproduce

1. Make a custom service e.g. name: "Google Calendar", https://calendar.google.com/
2. Open, "Google Calendar", login at "Google Calendar"
3. Make a different custom service e.g. "Google Calendar2", https://calendar.google.com/
4. Open "Google Calendar", the page already has credential data
5. 
### Expected behavior
"Google Calendar2" should open a blank login request page, without the credential data of "Google Calendar".

### Actual behavior
"Google Calendar2" is already login or required to retype password for the account set to "Google Calendar"

### ENVIRONMENT

> Hamsket 0.6.3
> Electron 13.5.1
> win32 x64 10.0.19043
> d86d4ef  (grafted, HEAD, tag: nightly, origin/d86d4ef90e9f2a32a8075db438437e32c34b17a5) Fri, 12 Nov 2021 21:13:57 -0800

> Does this happen upstream: yes, no, unknown, or N/A
AFAIK, no

**Comment by TheGoddessInari** [comment]
Mm. Okay. I just tried this, and I'm not seeing this behavior.
I made a service named "Google Calendar" with that URL. I log in.
I make a second one named "Google Calendar2", and several variations, and I get fresh login prompt, and no stored data.

Your instructions say, however,
> 4. Open "Google Calendar", the page already has credential data

If you open the first instance, and see the data you logged in for, that's expected? ^^; Unless it's a typo, which I expect it is, but, I can't reproduce this on Windows right now.

Even if I make 5 custom services, all called "Google Calendar", with the same name, they don't share storage. Every instance made should always have its own storage. No matter how many instances you make, it's all created with separate storage with increasing numbers.

The only way I can even think that you **could** get stale data, is if somehow got things confused, and it's simply reusing a previous instance **that was already deleted**, but that shouldn't be the case.

As far as I understand it, this is the line controlling the storage behavior in that way from ExtJS:
https://github.com/TheGoddessInari/hamsket/blob/master/app/model/Service.js#L4

This was committed by the original author, years before I knew of rambox, or they ignored all of the security stuff and angrily rejected baseline PRs to fix everything (especially security-wise) from anybody for something like over 18 months before I officially forked.

So, if I'm wrong about that controlling the behavior, or there's something I can do to helpfully track this down and fix it, I'm more than happy to! But my understanding is, at that point, it's an "ExtJS" thing, and if it has weird/buggy behavior, I'll need to either A( make an override for the bad behavior, which...the version stuff is stuck on is very old besides, or B( update to 7.x.whatever it is that they "allow" open source to use (but still not get any fixes or updates for). This has proven extremely elusive, as even if I follow the updating guide, and even updating **tool** they eventually released to the letter, and in theory, everything should work, even the most basic parts just...don't. Don't display coherent error messages, I've asked on the forums a number of times, and...yeah. They're kinda actively hostile to Open Source users...precisely because you're not paying fees. :P

I should probably upload the 'in-progress' bits of that to a separate branch, and ask for help, but...realistically, I've learned that it's much more likely that I'm going to write my own browser, layout engine, javascript engine, get EME certified by google, etc, and be able to use that to make a browser backend for the project that "doesn't suck", and...yeah. Total pipe dream, probably. 🦊Or somehow fork Chrome (as a few other things have more started to do), and somehow put up with 13+ hour builds that'd take well over 100GB of storage space on my development (and only) PC. 🥰

All of that's my overly technical way of saying...it's **probably** an ExtJS bug because nobody's touched the storage code or how it increments since 2016, during rambox's **initial** import to git, and the code it controls isn't a "user application" thing.

I probably overshared slightly, but hi. 🐱‍💻

**Comment by vurtomatic** [comment]
@TheGoddessInari Glad to see you're back and maintaining this! Hope all is well. Stay safe.

**Comment by ikenichiro** [comment]
`If you open the first instance, and see the data you logged in for, that's expected? ^^; Unless it's a typo, which I expect it is, but, I can't reproduce this on Windows right now.`
Yes, it was my typo. My bad. thank you for understanding my intentions ;)

After thinking few possibilities after reading your post, instead of updating the software with preserved local data, I completely deleted the local data inside  
`AppData\Roaming\Hamsket`
after uninstall, and the reinstalled fresh.

That seemed to solve my problem, and with it solved, I cannot reproduce the problem based on using the recent nightly only, So I'll close this issue since it seems that I was the only one having this issue.
So I think it may have been some kind of migration problem or something, as you pointed out, maybe or most likely from ExtJS,

Happy to see you active, and appreciate all of your work, including with your reply on this issue, which I am really happy to see.
